No.2 HTML/CSS基礎
morioka-masashi/sample_repository pull request #2
Opened 2024-02-20 13:46 UTC by morioka-masashi

# No.2 HTML/CSS基礎
課題の提出

# HTMLとCSSを用いてのレイアウト課題の作成
探り探りで体裁を整えたので一般的な用法や効率的な用法との違いがあれば、その点をご指摘いただきたいです。
ご確認よろしくお願いします。

2024-02-21 00:53 UTC, cin-sakino requested changes
ご提出ありがとうございます！
一つコメントさせていただきました！お手隙の際にご確認をお願いいたいします！🙏

2024-02-21 00:53 UTC, cin-sakino commented on html_css_basic/html_css_basic/lesson3/lesson03.html
> +	<img src="C:\Users\crout\geekation\html_css_basic\html_css_basic\lesson3\coffee.jpg"
ファイルの指定には`絶対パス`と`相対パス`があります。
今回は`相対パス`で指定してみましょう！

理由としては、このような場合`絶対パス`だと他の人のパソコンでは動かないからです。
元に、私のパソコンでは以下の場所に画像が格納されています。
```
/Applications/MAMP/htdocs/workspace/sample_repository/html_css_basic/html_css_basic/lesson3/lesson03.png
```
なのでhtml_css_basicをベースに`相対パス`で指定してみましょう！

2024-02-23 09:44 UTC, morioka-masashi commented on html_css_basic/html_css_basic/lesson3/lesson03.html
> +	<img src="C:\Users\crout\geekation\html_css_basic\html_css_basic\lesson3\coffee.jpg"
ご指摘ありがとうございます。
修正いたしましたのでご確認お願いいたします。

2024-02-27 11:13 UTC, cin-sakino approved these changes
💯

2024-02-28 19:13 UTC, closed without merging